### PR TITLE
Add Project.toml file, delete REQUIRE file, drop dependency on `Compat.jl`

### PR DESCRIPTION
**Pull request by DilumAluthge**
This pull request makes the following changes:
- Add support for Julia 0.7 and Julia 1
- Drop support for Julia 0.6
- Add `Project.toml` file
- Delete `REQUIRE` file
- Remove the dependency on `Compat.jl`

cc: @stevengj

### CODE REVIEW

**Comment by stevengj** [comment]
Thanks!  You should also update the appveyor and travis files to drop the 0.6 tests.

**Comment by DilumAluthge** [comment]
> Thanks! You should also update the appveyor and travis files to drop the 0.6 tests.

Done!

**Comment by DilumAluthge** [comment]
Bump @stevengj

**Comment by stevengj** [comment]
Thanks!

**Pull request merged**
